/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GameRouteImport } from './routes/game'
import { Route as SplatRouteImport } from './routes/$'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DestinasiIndexRouteImport } from './routes/destinasi/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as ArtikelIndexRouteImport } from './routes/artikel/index'
import { Route as DestinasiLeaderboardRouteImport } from './routes/destinasi/leaderboard'
import { Route as DashboardUserMenagementRouteImport } from './routes/dashboard/user-menagement'
import { Route as DashboardDestinationRouteImport } from './routes/dashboard/destination'
import { Route as DashboardArticlesRouteImport } from './routes/dashboard/articles'
import { Route as ArtikelArtikelIdRouteImport } from './routes/artikel/$artikelId'
import { Route as DashboardSettingsRouteRouteImport } from './routes/dashboard/settings/route'
import { Route as DestinasiDestinasiIdIndexRouteImport } from './routes/destinasi/$destinasiId/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as ApiCloudinaryDeleteByUrlRouteImport } from './routes/api/cloudinary/delete-by-url'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinasiIndexRoute = DestinasiIndexRouteImport.update({
  id: '/destinasi/',
  path: '/destinasi/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikelIndexRoute = ArtikelIndexRouteImport.update({
  id: '/artikel/',
  path: '/artikel/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinasiLeaderboardRoute = DestinasiLeaderboardRouteImport.update({
  id: '/destinasi/leaderboard',
  path: '/destinasi/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUserMenagementRoute = DashboardUserMenagementRouteImport.update({
  id: '/user-menagement',
  path: '/user-menagement',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDestinationRoute = DashboardDestinationRouteImport.update({
  id: '/destination',
  path: '/destination',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardArticlesRoute = DashboardArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ArtikelArtikelIdRoute = ArtikelArtikelIdRouteImport.update({
  id: '/artikel/$artikelId',
  path: '/artikel/$artikelId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRouteRoute = DashboardSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DestinasiDestinasiIdIndexRoute =
  DestinasiDestinasiIdIndexRouteImport.update({
    id: '/destinasi/$destinasiId/',
    path: '/destinasi/$destinasiId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSettingsRouteRoute,
} as any)
const ApiCloudinaryDeleteByUrlRoute =
  ApiCloudinaryDeleteByUrlRouteImport.update({
    id: '/api/cloudinary/delete-by-url',
    path: '/api/cloudinary/delete-by-url',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/game': typeof GameRoute
  '/dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/artikel/$artikelId': typeof ArtikelArtikelIdRoute
  '/dashboard/articles': typeof DashboardArticlesRoute
  '/dashboard/destination': typeof DashboardDestinationRoute
  '/dashboard/user-menagement': typeof DashboardUserMenagementRoute
  '/destinasi/leaderboard': typeof DestinasiLeaderboardRoute
  '/artikel/': typeof ArtikelIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/destinasi/': typeof DestinasiIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cloudinary/delete-by-url': typeof ApiCloudinaryDeleteByUrlRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/destinasi/$destinasiId/': typeof DestinasiDestinasiIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/game': typeof GameRoute
  '/artikel/$artikelId': typeof ArtikelArtikelIdRoute
  '/dashboard/articles': typeof DashboardArticlesRoute
  '/dashboard/destination': typeof DashboardDestinationRoute
  '/dashboard/user-menagement': typeof DashboardUserMenagementRoute
  '/destinasi/leaderboard': typeof DestinasiLeaderboardRoute
  '/artikel': typeof ArtikelIndexRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/destinasi': typeof DestinasiIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cloudinary/delete-by-url': typeof ApiCloudinaryDeleteByUrlRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/destinasi/$destinasiId': typeof DestinasiDestinasiIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/game': typeof GameRoute
  '/dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/artikel/$artikelId': typeof ArtikelArtikelIdRoute
  '/dashboard/articles': typeof DashboardArticlesRoute
  '/dashboard/destination': typeof DashboardDestinationRoute
  '/dashboard/user-menagement': typeof DashboardUserMenagementRoute
  '/destinasi/leaderboard': typeof DestinasiLeaderboardRoute
  '/artikel/': typeof ArtikelIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/destinasi/': typeof DestinasiIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cloudinary/delete-by-url': typeof ApiCloudinaryDeleteByUrlRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/destinasi/$destinasiId/': typeof DestinasiDestinasiIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/$'
    | '/game'
    | '/dashboard/settings'
    | '/artikel/$artikelId'
    | '/dashboard/articles'
    | '/dashboard/destination'
    | '/dashboard/user-menagement'
    | '/destinasi/leaderboard'
    | '/artikel/'
    | '/auth/'
    | '/dashboard/'
    | '/destinasi/'
    | '/api/auth/$'
    | '/api/cloudinary/delete-by-url'
    | '/dashboard/settings/'
    | '/destinasi/$destinasiId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/game'
    | '/artikel/$artikelId'
    | '/dashboard/articles'
    | '/dashboard/destination'
    | '/dashboard/user-menagement'
    | '/destinasi/leaderboard'
    | '/artikel'
    | '/auth'
    | '/dashboard'
    | '/destinasi'
    | '/api/auth/$'
    | '/api/cloudinary/delete-by-url'
    | '/dashboard/settings'
    | '/destinasi/$destinasiId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/$'
    | '/game'
    | '/dashboard/settings'
    | '/artikel/$artikelId'
    | '/dashboard/articles'
    | '/dashboard/destination'
    | '/dashboard/user-menagement'
    | '/destinasi/leaderboard'
    | '/artikel/'
    | '/auth/'
    | '/dashboard/'
    | '/destinasi/'
    | '/api/auth/$'
    | '/api/cloudinary/delete-by-url'
    | '/dashboard/settings/'
    | '/destinasi/$destinasiId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  GameRoute: typeof GameRoute
  ArtikelArtikelIdRoute: typeof ArtikelArtikelIdRoute
  DestinasiLeaderboardRoute: typeof DestinasiLeaderboardRoute
  ArtikelIndexRoute: typeof ArtikelIndexRoute
  AuthIndexRoute: typeof AuthIndexRoute
  DestinasiIndexRoute: typeof DestinasiIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCloudinaryDeleteByUrlRoute: typeof ApiCloudinaryDeleteByUrlRoute
  DestinasiDestinasiIdIndexRoute: typeof DestinasiDestinasiIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinasi/': {
      id: '/destinasi/'
      path: '/destinasi'
      fullPath: '/destinasi/'
      preLoaderRoute: typeof DestinasiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikel/': {
      id: '/artikel/'
      path: '/artikel'
      fullPath: '/artikel/'
      preLoaderRoute: typeof ArtikelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinasi/leaderboard': {
      id: '/destinasi/leaderboard'
      path: '/destinasi/leaderboard'
      fullPath: '/destinasi/leaderboard'
      preLoaderRoute: typeof DestinasiLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/user-menagement': {
      id: '/dashboard/user-menagement'
      path: '/user-menagement'
      fullPath: '/dashboard/user-menagement'
      preLoaderRoute: typeof DashboardUserMenagementRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/destination': {
      id: '/dashboard/destination'
      path: '/destination'
      fullPath: '/dashboard/destination'
      preLoaderRoute: typeof DashboardDestinationRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/articles': {
      id: '/dashboard/articles'
      path: '/articles'
      fullPath: '/dashboard/articles'
      preLoaderRoute: typeof DashboardArticlesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/artikel/$artikelId': {
      id: '/artikel/$artikelId'
      path: '/artikel/$artikelId'
      fullPath: '/artikel/$artikelId'
      preLoaderRoute: typeof ArtikelArtikelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/destinasi/$destinasiId/': {
      id: '/destinasi/$destinasiId/'
      path: '/destinasi/$destinasiId'
      fullPath: '/destinasi/$destinasiId/'
      preLoaderRoute: typeof DestinasiDestinasiIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/api/cloudinary/delete-by-url': {
      id: '/api/cloudinary/delete-by-url'
      path: '/api/cloudinary/delete-by-url'
      fullPath: '/api/cloudinary/delete-by-url'
      preLoaderRoute: typeof ApiCloudinaryDeleteByUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardSettingsRouteRouteChildren {
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardSettingsRouteRouteChildren: DashboardSettingsRouteRouteChildren =
  {
    DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  }

const DashboardSettingsRouteRouteWithChildren =
  DashboardSettingsRouteRoute._addFileChildren(
    DashboardSettingsRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardSettingsRouteRoute: typeof DashboardSettingsRouteRouteWithChildren
  DashboardArticlesRoute: typeof DashboardArticlesRoute
  DashboardDestinationRoute: typeof DashboardDestinationRoute
  DashboardUserMenagementRoute: typeof DashboardUserMenagementRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardSettingsRouteRoute: DashboardSettingsRouteRouteWithChildren,
  DashboardArticlesRoute: DashboardArticlesRoute,
  DashboardDestinationRoute: DashboardDestinationRoute,
  DashboardUserMenagementRoute: DashboardUserMenagementRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  GameRoute: GameRoute,
  ArtikelArtikelIdRoute: ArtikelArtikelIdRoute,
  DestinasiLeaderboardRoute: DestinasiLeaderboardRoute,
  ArtikelIndexRoute: ArtikelIndexRoute,
  AuthIndexRoute: AuthIndexRoute,
  DestinasiIndexRoute: DestinasiIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCloudinaryDeleteByUrlRoute: ApiCloudinaryDeleteByUrlRoute,
  DestinasiDestinasiIdIndexRoute: DestinasiDestinasiIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
