/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DestinasiIndexRouteImport } from './routes/destinasi/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardDestinationRouteImport } from './routes/dashboard/destination'
import { Route as DashboardArticlesRouteImport } from './routes/dashboard/articles'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as DashboardSettingsRouteRouteImport } from './routes/dashboard/settings/route'
import { Route as DestinasiDestinasiIdIndexRouteImport } from './routes/destinasi/$destinasiId/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardSettingsPasswordRouteImport } from './routes/dashboard/settings/password'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinasiIndexRoute = DestinasiIndexRouteImport.update({
  id: '/destinasi/',
  path: '/destinasi/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDestinationRoute = DashboardDestinationRouteImport.update({
  id: '/destination',
  path: '/destination',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardArticlesRoute = DashboardArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRouteRoute = DashboardSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DestinasiDestinasiIdIndexRoute =
  DestinasiDestinasiIdIndexRouteImport.update({
    id: '/destinasi/$destinasiId/',
    path: '/destinasi/$destinasiId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSettingsRouteRoute,
} as any)
const DashboardSettingsPasswordRoute =
  DashboardSettingsPasswordRouteImport.update({
    id: '/password',
    path: '/password',
    getParentRoute: () => DashboardSettingsRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/dashboard/articles': typeof DashboardArticlesRoute
  '/dashboard/destination': typeof DashboardDestinationRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/destinasi': typeof DestinasiIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/settings/password': typeof DashboardSettingsPasswordRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/destinasi/$destinasiId': typeof DestinasiDestinasiIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/dashboard/articles': typeof DashboardArticlesRoute
  '/dashboard/destination': typeof DashboardDestinationRoute
  '/dashboard': typeof DashboardIndexRoute
  '/destinasi': typeof DestinasiIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/settings/password': typeof DashboardSettingsPasswordRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/destinasi/$destinasiId': typeof DestinasiDestinasiIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/dashboard/articles': typeof DashboardArticlesRoute
  '/dashboard/destination': typeof DashboardDestinationRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/destinasi/': typeof DestinasiIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/settings/password': typeof DashboardSettingsPasswordRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/destinasi/$destinasiId/': typeof DestinasiDestinasiIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/$'
    | '/dashboard/settings'
    | '/login'
    | '/register'
    | '/dashboard/articles'
    | '/dashboard/destination'
    | '/dashboard/'
    | '/destinasi'
    | '/api/auth/$'
    | '/dashboard/settings/password'
    | '/dashboard/settings/'
    | '/destinasi/$destinasiId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/login'
    | '/register'
    | '/dashboard/articles'
    | '/dashboard/destination'
    | '/dashboard'
    | '/destinasi'
    | '/api/auth/$'
    | '/dashboard/settings/password'
    | '/dashboard/settings'
    | '/destinasi/$destinasiId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/$'
    | '/dashboard/settings'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/dashboard/articles'
    | '/dashboard/destination'
    | '/dashboard/'
    | '/destinasi/'
    | '/api/auth/$'
    | '/dashboard/settings/password'
    | '/dashboard/settings/'
    | '/destinasi/$destinasiId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  DestinasiIndexRoute: typeof DestinasiIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  DestinasiDestinasiIdIndexRoute: typeof DestinasiDestinasiIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinasi/': {
      id: '/destinasi/'
      path: '/destinasi'
      fullPath: '/destinasi'
      preLoaderRoute: typeof DestinasiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/destination': {
      id: '/dashboard/destination'
      path: '/destination'
      fullPath: '/dashboard/destination'
      preLoaderRoute: typeof DashboardDestinationRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/articles': {
      id: '/dashboard/articles'
      path: '/articles'
      fullPath: '/dashboard/articles'
      preLoaderRoute: typeof DashboardArticlesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/destinasi/$destinasiId/': {
      id: '/destinasi/$destinasiId/'
      path: '/destinasi/$destinasiId'
      fullPath: '/destinasi/$destinasiId'
      preLoaderRoute: typeof DestinasiDestinasiIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/settings/password': {
      id: '/dashboard/settings/password'
      path: '/password'
      fullPath: '/dashboard/settings/password'
      preLoaderRoute: typeof DashboardSettingsPasswordRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardSettingsRouteRouteChildren {
  DashboardSettingsPasswordRoute: typeof DashboardSettingsPasswordRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardSettingsRouteRouteChildren: DashboardSettingsRouteRouteChildren =
  {
    DashboardSettingsPasswordRoute: DashboardSettingsPasswordRoute,
    DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  }

const DashboardSettingsRouteRouteWithChildren =
  DashboardSettingsRouteRoute._addFileChildren(
    DashboardSettingsRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardSettingsRouteRoute: typeof DashboardSettingsRouteRouteWithChildren
  DashboardArticlesRoute: typeof DashboardArticlesRoute
  DashboardDestinationRoute: typeof DashboardDestinationRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardSettingsRouteRoute: DashboardSettingsRouteRouteWithChildren,
  DashboardArticlesRoute: DashboardArticlesRoute,
  DashboardDestinationRoute: DashboardDestinationRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  DestinasiIndexRoute: DestinasiIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  DestinasiDestinasiIdIndexRoute: DestinasiDestinasiIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
